Объедены страницы с событиями
Druki-ru/content pull request #106
Opened 2021-08-30 20:17 UTC by chesn0k

2021-08-30 20:25 UTC, chesn0k commented on docs/ru/drupal/9/events/index.md
> +### Рекомендация регистрации названий событий
Возможно стоит сократить до:
> Рекомендация регистрации  событий.

По контексту думаю и так понятно что мы регистрируем не сам объект события.

2021-08-31 03:59 UTC, Niklan requested changes
Спасибо, лишь небольшая опечатка ;)

2021-08-31 03:59 UTC, Niklan commented on docs/ru/drupal/9/events/index.md
> +  - подписчик на собыитие
> собыитие

Опечатка.

2021-08-31 04:00 UTC, Niklan commented on docs/ru/drupal/9/events/index.md
> +### Рекомендация регистрации названий событий
Да, нормально, можно сократить.

2021-08-31 06:44 UTC, Niklan approved these changes
Спасибо!

2021-08-31 06:45 UTC, merged